export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOG_OUT = 'LOG_OUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const MAIN_VIDEOS_SUCCESS = 'MAIN_VIDEOS_SUCCESS';
export const MAIN_VIDEOS_FAIL = 'MAIN_VIDEOS_FAIL';
export const MAIN_VIDEOS_REQUEST = 'MAIN_VIDEOS_REQUEST';

export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAIL = 'SELECTED_VIDEO_FAIL';
export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST';

export const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';
export const RELATED_VIDEO_FAIL = 'RELATED_VIDEO_FAIL';
export const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';

export const SEARCHED_VIDEO_SUCCESS = 'SEARCHED_VIDEO_SUCCESS';
export const SEARCHED_VIDEO_FAIL = 'SEARCHED_VIDEO_FAIL';
export const SEARCHED_VIDEO_REQUEST = 'SEARCHED_VIDEO_REQUEST';

export const CHANNEL_INFO_SUCCESS = 'CHANNEL_INFO_SUCCESS';
export const CHANNEL_INFO_FAIL = 'CHANNEL_INFO_FAIL';
export const CHANNEL_INFO_REQUEST = 'CHANNEL_INFO_REQUEST';

export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';

export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS';
export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL';
export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';
