export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOG_OUT = 'LOG_OUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const MAIN_VIDEOS_SUCCESS = 'MAIN_VIDEOS_SUCCESS';
export const MAIN_VIDEOS_FAIL = 'MAIN_VIDEOS_FAIL';
export const MAIN_VIDEOS_REQUEST = 'MAIN_VIDEOS_REQUEST';

export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAIL = 'SELECTED_VIDEO_FAIL';
export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST';

export const CHANNEL_INFO_SUCCESS = 'CHANNEL_INFO_SUCCESS';
export const CHANNEL_INFO_FAIL = 'CHANNEL_INFO_FAIL';
export const CHANNEL_INFO_REQUEST = 'CHANNEL_INFO_REQUEST';

export const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';
